# Generated by Django 6.0.7 on 2026-08-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_clue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('accused_character_name', models.CharField(help_text='Foydalanuvchi kim aybdor deb hisoblaydi', max_length=100)),
                ('reasoning', models.TextField(help_text='Foydalanuvchining asoslashi')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cases.case')),
            ],
        ),
    ]
