# Generated by Django 6.0.7 on 2026-08-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'Personaj')], max_length=10)),
                ('content', models.TextField()),
                ('session_id', models.CharField(help_text='Brauzer sessiyasini ajratish uchun', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.character')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
