# Generated by Django 6.0.7 on 2026-08-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='scenes/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('personality', models.TextField(help_text='Personajning xarakteri, gapirish uslubi')),
                ('knowledge', models.TextField(help_text="Personaj biladigan haqiqiy ma'lumotlar")),
                ('secrets', models.TextField(help_text='Personaj yashiradigan, oson aytmaydigan sirlar')),
                ('is_guilty', models.BooleanField(default=False, help_text='Bu personaj aybdormi?')),
                ('lying_tendency', models.CharField(choices=[('honest', 'Har doim rost gapiradi'), ('evasive', "Savolni chalg'itadi, lekin ochiq yolg'on gapirmaydi"), ('deceptive', "Kerak bo'lsa ochiq yolg'on gapiradi")], default='honest', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='cases.case')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='cases.scene')),
            ],
        ),
    ]
