# Generated by Django 6.0.7 on 2026-08-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='Foydalanuvchi yozgan dalil matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='cases.case')),
                ('source_character', models.ForeignKey(blank=True, help_text='Bu dalil qaysi personajdan olingan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.character')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
