# Generated by Django 6.0.7 on 2026-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alibi',
            field=models.TextField(blank=True, help_text='Voqea kuni qayerda, qachon nima qilgani (vaqt bilan yozing, masalan: 20:00 — oshxonada edim)'),
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.TextField(blank=True, help_text='Boshqa personajlar bilan munosabati (masalan: Xizmatkorni yoqtirmaydi, chunki...)'),
        ),
    ]
