# Generated by Django 6.0.7 on 2026-08-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_scene_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='knowledge',
            field=models.TextField(blank=True, help_text="Personaj biladigan haqiqiy ma'lumotlar"),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True, help_text='Personajning xarakteri, gapirish uslubi'),
        ),
        migrations.AlterField(
            model_name='character',
            name='secrets',
            field=models.TextField(blank=True, help_text='Personaj yashiradigan, oson aytmaydigan sirlar'),
        ),
    ]
